naam = input("hoe heet je? ")
adres = input("wat is je adres? ")
postcode = input("wat is je postcode? ")
woonplaats = input("waar woon je? ")

print("  ----------------------------------------------------")
print(f"|  naam      : {naam}")
print(f"|  adres     : {adres}")
print(f"|  postcode  : {postcode}")
print(f"|  woonplaats: {woonplaats}")
print("  ----------------------------------------------------")